branch-defaults:
  master:
    environment: personal-site
    group_suffix: null
global:
  application_name: p_site
  branch: null
  default_ec2_keyname: personal
  default_platform: Node.js
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: personal
  repository: null
  sc: git
  workspace_type: Application
